### PR TITLE
Parse target triples

### LINKED ISSUE #76: Implement TRIPLE
See [here](https://github.com/GaloisInc/llvm-pretty-bc-parser/blob/87d32a45dfba3315f53075357e7bd27102469967/src/Data/LLVM/BitCode/IR/Module.hs#L169)

Depends on the completion of https://github.com/elliottt/llvm-pretty/issues/21

### PR DESCRIPTION
**Pull request by langston-barrett**
Fixes #76

### CODE REVIEW

**Comment by langston-barrett** [comment]
The round-tripping tests are failling, likely because `llvm-pretty` doesn't yet *print* target triples. Will need an upstream fix. https://github.com/elliottt/llvm-pretty/issues/100

**Comment by langston-barrett** [comment]
Upstream fix implemented and merged, submodule updated here and the tests pass. Ready for review!

**Comment by RyanGlScott** [comment]
This looks reasonable to me. Does this pass the `llvm-quick-fuzz` job?

**Comment by langston-barrett** [comment]
> This looks reasonable to me. Does this pass the llvm-quick-fuzz job?

Good question, let's find out! https://github.com/langston-barrett/llvm-pretty-bc-parser/actions/runs/3138649071

**Comment by langston-barrett** [comment]
> This looks reasonable to me. Does this pass the llvm-quick-fuzz job?

TBH, this probably isn't the best test of this functionality - `llvm-quick-fuzz` tests by compiling C code generated by CSmith, so all of the generated modules likely have the same target triple. #155 would probably be better...

**Review by kquick — APPROVED** [review]

**Review by RyanGlScott — APPROVED** [review]
> TBH, this probably isn't the best test of this functionality - `llvm-quick-fuzz` tests by compiling C code generated by CSmith, so all of the generated modules likely have the same target triple (namely, the triple corresponding to the CI runner).

Oops, quite so. In any case, thanks for being thorough and checking anyway.

**Pull request merged**
